### ISSUE TITLE
Add special field for non-Slack PAX

### ISSUE THREAD

**Issue by willhlaw** [F3Nation-Community/slackblast#11]
As a Q submitting the backblast, I would like the form to separate out FNG field with “Not In Slack” field so that it is clearer what to do with PAX that are not in Slack and thus not taggable.

Humbly requested by Dilfer (Puget Sound) and favored also by Huggies (Phoenix, AZ).

**Comment by willhlaw** [comment]
From Huggies: 

> our Pax started adding "(not fng)" to Pax in the fng field cause they're just not in slack.  It would be nice to have an additional field that is just concatenated to the Pax part of the post instead of all in fng.

**Comment by willhlaw** [comment]
Huggies: the new field should also post along with the PAX field in Slack to align with PAXMiner's instructions. https://f3stlouis.com/paxminer/

> Backblast! (Give your workout a creative name, make sure the first word of the message is Backblast with NO SPACES before it)
Date: Day, MM/DD/YY (note – the format is pretty flexible, you can use 05/05/2021 or Wednesday, May 5, 2021. If entering on your phone, make sure your phone doesn’t turn this into a telephone# hyperlink like seems to happen sometimes… if the date turns blue, your phone made it a hyperlink and it will break)
AO: AO Name (use the channel name if possible like #ao_wet_willy)
PAX: Tag every PAX in attendance with @NAME. Make sure they’re tagged/blue. If not on Slack, just list their F3 name.
FNGs: Say the total # of FNGs, then list their new F3 names here separated by commas. They mostly won’t have Slack accounts set up yet. Even if they do, list them here.
Q: tag Q and  co-Q if applicable with @NAME. Q first,  then Co-Q second.
Total: Total number including Q, PAX, and FNGs. Number only, no text.
Conditions: How was the morning? Get colorful.

**Comment by evanpetzoldt** [comment]
Done in latest version!
