### ISSUE TITLE
Ensure PAX Count value is a whole number

### ISSUE THREAD

**Issue by willhlaw** [F3Nation-Community/slackblast#12]
Because tools like PAXMiner are looking for a whole number, e.g. 7, then 'seven' should not be allowed in the slackblast post. 

Proposals:

a) we can make maximum length 3 so 100 can be typed in but not seven. May catch a lot of these cases.
b) can look into updating the label to make it clear a number is expected. May also add a validation message depending on Slack's modal capability - which increases the interactivity and number of communications between slack and the server and overall making it nearly twice as complicated
c) the server can read the input and if it is not an integer, then server can parse the PAX and non-PAX names by hand to come up with the count

**Comment by evanpetzoldt** [comment]
No longer relevant to Slackblast, as it now directly interfaces with the db and is not read by PAXMiner
