### ISSUE TITLE
Strava Integration

### ISSUE THREAD

**Issue by michaeldpotter** [F3Nation-Community/slackblast#24]
Hello,
I'm not sure if I'm in the right place for this, but I'm having an issue with the Strava integration. When I click on the "Connect to Strava" button in the SlackBlast, a pop-up window launches, and says "Loading, do not close", but just hangs there indefinitely.

I've tried logged out of Slack and back in, and that did not help. I've tried it from the Slack mobile app as well, and that has the same results.

Is there a way to fix this, or things I could try?

![Uploading Screenshot 2024-01-04 at 7.17.48 AM.png…]()

**Comment by evanpetzoldt** [comment]
Is this still a problem? I made a push yesterday that may have fixed it.

**Comment by michaeldpotter** [comment]
I just tried it, and it's still not working for me. I can see that it's working for others on our Slack instance.

Someone would have to do a pull to incorporate the code change you made right? Or is there some other method by which it gets updated on our particular Slack instance?

**Comment by evanpetzoldt** [comment]
Hmm ok, I'll check the logs. What is your F3 name and region? That will help with lookup.

No it's a shared web app, so updates go out to all regions as soon as I push changes

**Comment by michaeldpotter** [comment]
Ok gotcha.Region: WichitaAO: WildwestF3 Name: ChubbsThanks so much for your help!Sent from my iPhoneOn Jan 6, 2024, at 4:57 PM, Evan Petzoldt ***@***.***> wrote:﻿
Hmm ok, I'll check the logs. What is your F3 name and region? That will help with lookup.
No it's a shared web app, so updates go out to all regions as soon as I push changes

**Comment by evanpetzoldt** [comment]
It looks like there's a problem with your authorization. I just tried resetting the integration for your user, try using the button again and re-authorizing

**Comment by michaeldpotter** [comment]
Success! It prompted me to authorize the access in Strava. It did throw up an error, but when I went back and connected the activity in Slack, it gave me a list of activities to connect. Attaching error page screen shot.
<img width="1397" alt="Screenshot 2024-01-08 at 9 27 26 AM" src="https://github.com/F3Nation-Community/slackblast/assets/6589130/d088ebaa-8654-43f8-b560-0ed237ae57cc">

This is the API call that was in the address bar for that screenshot (I obfuscated some of the code in case it's sensitive, let me know if you need it)   :
https://n1tbdh3ak9.execute-api.us-east-2.amazonaws.com/Prod/exchange_token?state=T02F4F******-********32N7&code=6c500bb****************5aee1b4dae3b2ca2cd&scope=read,activity:write,activity:read

**Comment by michaeldpotter** [comment]
Thanks so much for helping me out on this!

**Comment by evanpetzoldt** [comment]
Awesome! Yeah I haven't figured out how to prevent that authorization error when you first connect. I also don't know why your token in particular stopped working, but i guess we'll see if it starts happening to others
