### ISSUE TITLE
Enhancement request - Hide edit backblast if not Q/CO-Q/Slack Admin

### ISSUE THREAD

**Issue by andystlGit** [F3Nation-Community/slackblast#65]
Would prefer if Edit Backblast was not shown for PAX who were not the Q/Co-Q/Slack Admin.  

I realize the code does not allow for editing, but would be cleaner if the option was not displayed and reduce confusion from the PAX (as well as the number of times I have to explain this)

**Comment by evanpetzoldt** [comment]
Unfortunately, this is not possible. Any buttons on a post have to be visible to all users. Closing...
